// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterStatus int32

const (
	RegisterStatus_REGISTER_STATUS_UNSPECIFIED RegisterStatus = 0
	RegisterStatus_USER_ALREADY_EXISTS         RegisterStatus = 1
	RegisterStatus_OTP_SENT                    RegisterStatus = 2
	RegisterStatus_REGISTER_ERROR              RegisterStatus = 3
)

// Enum value maps for RegisterStatus.
var (
	RegisterStatus_name = map[int32]string{
		0: "REGISTER_STATUS_UNSPECIFIED",
		1: "USER_ALREADY_EXISTS",
		2: "OTP_SENT",
		3: "REGISTER_ERROR",
	}
	RegisterStatus_value = map[string]int32{
		"REGISTER_STATUS_UNSPECIFIED": 0,
		"USER_ALREADY_EXISTS":         1,
		"OTP_SENT":                    2,
		"REGISTER_ERROR":              3,
	}
)

func (x RegisterStatus) Enum() *RegisterStatus {
	p := new(RegisterStatus)
	*p = x
	return p
}

func (x RegisterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_proto_enumTypes[0].Descriptor()
}

func (RegisterStatus) Type() protoreflect.EnumType {
	return &file_proto_auth_proto_enumTypes[0]
}

func (x RegisterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterStatus.Descriptor instead.
func (RegisterStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

type ConfirmRegistrationStatus int32

const (
	ConfirmRegistrationStatus_CONFIRM_STATUS_UNSPECIFIED ConfirmRegistrationStatus = 0
	ConfirmRegistrationStatus_CONFIRM_SUCCESS            ConfirmRegistrationStatus = 1
	ConfirmRegistrationStatus_INVALID_CODE               ConfirmRegistrationStatus = 2
	ConfirmRegistrationStatus_CODE_EXPIRED               ConfirmRegistrationStatus = 3
	ConfirmRegistrationStatus_USER_NOT_FOUND_CODE        ConfirmRegistrationStatus = 4
	ConfirmRegistrationStatus_CONFIRM_ERROR              ConfirmRegistrationStatus = 5
)

// Enum value maps for ConfirmRegistrationStatus.
var (
	ConfirmRegistrationStatus_name = map[int32]string{
		0: "CONFIRM_STATUS_UNSPECIFIED",
		1: "CONFIRM_SUCCESS",
		2: "INVALID_CODE",
		3: "CODE_EXPIRED",
		4: "USER_NOT_FOUND_CODE",
		5: "CONFIRM_ERROR",
	}
	ConfirmRegistrationStatus_value = map[string]int32{
		"CONFIRM_STATUS_UNSPECIFIED": 0,
		"CONFIRM_SUCCESS":            1,
		"INVALID_CODE":               2,
		"CODE_EXPIRED":               3,
		"USER_NOT_FOUND_CODE":        4,
		"CONFIRM_ERROR":              5,
	}
)

func (x ConfirmRegistrationStatus) Enum() *ConfirmRegistrationStatus {
	p := new(ConfirmRegistrationStatus)
	*p = x
	return p
}

func (x ConfirmRegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmRegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_proto_enumTypes[1].Descriptor()
}

func (ConfirmRegistrationStatus) Type() protoreflect.EnumType {
	return &file_proto_auth_proto_enumTypes[1]
}

func (x ConfirmRegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmRegistrationStatus.Descriptor instead.
func (ConfirmRegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

type RefreshTokenStatus int32

const (
	RefreshTokenStatus_REFRESH_STATUS_UNSPECIFIED RefreshTokenStatus = 0
	RefreshTokenStatus_REFRESH_SUCCESS            RefreshTokenStatus = 1
	RefreshTokenStatus_INVALID_REFRESH_TOKEN      RefreshTokenStatus = 2
	RefreshTokenStatus_EXPIRED_REFRESH_TOKEN      RefreshTokenStatus = 3
	RefreshTokenStatus_REFRESH_ERROR              RefreshTokenStatus = 4
)

// Enum value maps for RefreshTokenStatus.
var (
	RefreshTokenStatus_name = map[int32]string{
		0: "REFRESH_STATUS_UNSPECIFIED",
		1: "REFRESH_SUCCESS",
		2: "INVALID_REFRESH_TOKEN",
		3: "EXPIRED_REFRESH_TOKEN",
		4: "REFRESH_ERROR",
	}
	RefreshTokenStatus_value = map[string]int32{
		"REFRESH_STATUS_UNSPECIFIED": 0,
		"REFRESH_SUCCESS":            1,
		"INVALID_REFRESH_TOKEN":      2,
		"EXPIRED_REFRESH_TOKEN":      3,
		"REFRESH_ERROR":              4,
	}
)

func (x RefreshTokenStatus) Enum() *RefreshTokenStatus {
	p := new(RefreshTokenStatus)
	*p = x
	return p
}

func (x RefreshTokenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshTokenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_proto_enumTypes[2].Descriptor()
}

func (RefreshTokenStatus) Type() protoreflect.EnumType {
	return &file_proto_auth_proto_enumTypes[2]
}

func (x RefreshTokenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshTokenStatus.Descriptor instead.
func (RefreshTokenStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RegisterStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=auth.RegisterStatus" json:"status,omitempty"`
	OtpId         string                 `protobuf:"bytes,2,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"` // ID для проверки OTP
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`          // Сообщение об ошибке или успехе
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetStatus() RegisterStatus {
	if x != nil {
		return x.Status
	}
	return RegisterStatus_REGISTER_STATUS_UNSPECIFIED
}

func (x *RegisterResponse) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpId         string                 `protobuf:"bytes,1,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRegistrationRequest) Reset() {
	*x = ConfirmRegistrationRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRegistrationRequest) ProtoMessage() {}

func (x *ConfirmRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRegistrationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmRegistrationRequest) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *ConfirmRegistrationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfirmRegistrationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        ConfirmRegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=auth.ConfirmRegistrationStatus" json:"status,omitempty"`
	UserId        int64                     `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // возвращаем ID пользователя, если успех
	Token         string                    `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                                   // JWT или session, чтобы сразу работать дальше
	RefreshToken  string                    `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // для обновления токена
	Message       string                    `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                               // например: "Регистрация успешно подтверждена"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRegistrationResponse) Reset() {
	*x = ConfirmRegistrationResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRegistrationResponse) ProtoMessage() {}

func (x *ConfirmRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRegistrationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmRegistrationResponse) GetStatus() ConfirmRegistrationStatus {
	if x != nil {
		return x.Status
	}
	return ConfirmRegistrationStatus_CONFIRM_STATUS_UNSPECIFIED
}

func (x *ConfirmRegistrationResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmRegistrationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConfirmRegistrationResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ConfirmRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RefreshTokenStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=auth.RefreshTokenStatus" json:"status,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`     // новый JWT токен
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // сообщение об ошибке или успехе
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResponse) GetStatus() RefreshTokenStatus {
	if x != nil {
		return x.Status
	}
	return RefreshTokenStatus_REFRESH_STATUS_UNSPECIFIED
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"q\n" +
	"\x10RegisterResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.auth.RegisterStatusR\x06status\x12\x15\n" +
	"\x06otp_id\x18\x02 \x01(\tR\x05otpId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"G\n" +
	"\x1aConfirmRegistrationRequest\x12\x15\n" +
	"\x06otp_id\x18\x01 \x01(\tR\x05otpId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xc4\x01\n" +
	"\x1bConfirmRegistrationResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.auth.ConfirmRegistrationStatusR\x06status\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"x\n" +
	"\x14RefreshTokenResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.auth.RefreshTokenStatusR\x06status\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*l\n" +
	"\x0eRegisterStatus\x12\x1f\n" +
	"\x1bREGISTER_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13USER_ALREADY_EXISTS\x10\x01\x12\f\n" +
	"\bOTP_SENT\x10\x02\x12\x12\n" +
	"\x0eREGISTER_ERROR\x10\x03*\xa0\x01\n" +
	"\x19ConfirmRegistrationStatus\x12\x1e\n" +
	"\x1aCONFIRM_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCONFIRM_SUCCESS\x10\x01\x12\x10\n" +
	"\fINVALID_CODE\x10\x02\x12\x10\n" +
	"\fCODE_EXPIRED\x10\x03\x12\x17\n" +
	"\x13USER_NOT_FOUND_CODE\x10\x04\x12\x11\n" +
	"\rCONFIRM_ERROR\x10\x05*\x92\x01\n" +
	"\x12RefreshTokenStatus\x12\x1e\n" +
	"\x1aREFRESH_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fREFRESH_SUCCESS\x10\x01\x12\x19\n" +
	"\x15INVALID_REFRESH_TOKEN\x10\x02\x12\x19\n" +
	"\x15EXPIRED_REFRESH_TOKEN\x10\x03\x12\x11\n" +
	"\rREFRESH_ERROR\x10\x042\xeb\x01\n" +
	"\vAuthService\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x12Z\n" +
	"\x13ConfirmRegistration\x12 .auth.ConfirmRegistrationRequest\x1a!.auth.ConfirmRegistrationResponse\x12E\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponseB\bZ\x06proto/b\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_auth_proto_goTypes = []any{
	(RegisterStatus)(0),                 // 0: auth.RegisterStatus
	(ConfirmRegistrationStatus)(0),      // 1: auth.ConfirmRegistrationStatus
	(RefreshTokenStatus)(0),             // 2: auth.RefreshTokenStatus
	(*RegisterRequest)(nil),             // 3: auth.RegisterRequest
	(*RegisterResponse)(nil),            // 4: auth.RegisterResponse
	(*ConfirmRegistrationRequest)(nil),  // 5: auth.ConfirmRegistrationRequest
	(*ConfirmRegistrationResponse)(nil), // 6: auth.ConfirmRegistrationResponse
	(*RefreshTokenRequest)(nil),         // 7: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),        // 8: auth.RefreshTokenResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	0, // 0: auth.RegisterResponse.status:type_name -> auth.RegisterStatus
	1, // 1: auth.ConfirmRegistrationResponse.status:type_name -> auth.ConfirmRegistrationStatus
	2, // 2: auth.RefreshTokenResponse.status:type_name -> auth.RefreshTokenStatus
	3, // 3: auth.AuthService.Register:input_type -> auth.RegisterRequest
	5, // 4: auth.AuthService.ConfirmRegistration:input_type -> auth.ConfirmRegistrationRequest
	7, // 5: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	4, // 6: auth.AuthService.Register:output_type -> auth.RegisterResponse
	6, // 7: auth.AuthService.ConfirmRegistration:output_type -> auth.ConfirmRegistrationResponse
	8, // 8: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		EnumInfos:         file_proto_auth_proto_enumTypes,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
